baseURL = "https://wenfeng-gao.github.io/"
languageCode = "en-us"
title = "Je pense donc je suis"
tags = ["k8s", "docker", "k8s-kubelet"]
theme = "beautifulhugo"
#disqusShortname = "https://wenfeng-gao.github.io"

[Params]
  #subtitle = "Build a beautiful and simple website in minutes"
  logo = "img/avatar-icon.png" # Expecting square dimensions
  favicon = "img/favicon.ico"
  commit = false
  rss = true
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = false
  delayDisqus = true
  showRelatedPosts = true

[Author]
  name = "Wenfeng Gao"
  email = "elricfeng@gmail.com"
  googleplus = "103999582027187063854" # or xxxxxxxxxxxxxxxxxxxxx
  github = "Wenfeng-GAO"
  # linkedin = "username"
  stackoverflow = "users/4262814/wenfeng"
  paypal = "elricfeng"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3
